---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "Get timestamp for docker tag"
    shell: "(date +%Y%m%d%H%M%S)"
    register: tag

  - name: Print tag
    debug:
      var: tag.stdout

  # - name: Build rag_data_pipeline container image
  #   community.general.docker_image:
  #     build:
  #       path: /rag_data_pipeline
  #       platform: linux/amd64/v2
  #     name: gcr.io/{{ gcp_project }}/rag-data-pipeline:{{ tag.stdout }}
  #     source: build

  # - name: Push rag_data_pipeline image to GCR
  #   community.general.docker_image:
  #     name: gcr.io/{{ gcp_project }}/rag-data-pipeline:{{ tag.stdout }}
  #     repository: gcr.io/{{ gcp_project }}/rag-data-pipeline
  #     push: yes
  #     source: local

  - name: Build service container image
    community.general.docker_image:
      build:
        path: /service
        platform: linux/amd64/v2
      name: gcr.io/{{ gcp_project }}/service:{{ tag.stdout }}
      source: build

  - name: Push service image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/service:{{ tag.stdout }}
      repository: gcr.io/{{ gcp_project }}/service
      push: yes
      source: local

  - name: "Save docker tag"
    shell: echo {{ tag.stdout }} > .docker-tag

  - name: "Remove all unused containers"
    shell: docker system prune -a -f
