networks:
    default:
        name: app-network
        external: true
services:
    vector-db-cli:
        image: llm-rag-datapipeline
        container_name: llm-rag-datapipeline
        volumes:
          - ../../../ac215_closedai:/app
          - ../../secrets:/secrets  # Mount your secrets directory
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
            CHROMADB_HOST: llm-rag-chromadb
            CHROMADB_PORT: 8000
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: llm-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE