name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [data_versioning, finetune_data, finetune_model, rag_data_pipeline, rag_model]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker Image for ${{ matrix.service }}
      run: |
        docker build -t ${{ matrix.service }} ./src/${{ matrix.service }}

    - name: Run Linting
      run: |
        flake8 ./src/${{ matrix.service }} --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./src/${{ matrix.service }} --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests
      run: |
        docker run ${{ matrix.service }} pytest --junitxml=test-results/${{ matrix.service }}_results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.service }}
        path: test-results/${{ matrix.service }}_results.xml
