name: my_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - user-agent
      - requests
      - google-cloud-storage
      - google-generativeai
      - google-cloud-aiplatform
      - pandas
      - langchain
      - llama-index
      - chromadb
      - langchain-community
      - flask
      - pytest
      - pytest-mock
      - pytest-flask
      - scikit-learn
      - selenium
      - pytest-cov
