name: Pre-Commit Checks

on:
  pull_request:
    branches:
      - main
      - milestone4
  push:
    branches:
      - main
      - milestone4

permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pre-commit and flake8
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit flake8 pytest flask chromadb vertexai pipenv langchain


      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Show flake8 configuration (Optional)
        run: flake8 --version

      # - name: Set up Google credentials
      #   run: |
      #     mkdir -p ${{ github.workspace }}/secrets
      #     echo "${{ secrets.GOOGLE_CREDENTIALS }}" > ${{ github.workspace }}/secrets/llm-service-account.json
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/secrets/llm-service-account.json

      # - name: Authenticate with Google Cloud
      #   run: |
      #     gcloud auth activate-service-account --key-file=${{ github.workspace }}/secrets/llm-service-account.json
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/secrets/llm-service-account.json

      # - name: Verify Authentication
      #   run: gcloud auth list


      - name: Run tests
        env:
          BASE_DIR: ${{ github.workspace }}
          SECRETS_DIR: ${{ github.workspace }}/secrets/
          GCP_PROJECT: "xenon-depth-434717-n0"
          GCS_BUCKET_NAME: "closed-ai"
          GCS_RAG_BUCKET_NAME: "closed-ai-rag"
          GOOGLE_APPLICATION_CREDENTIALS: "/secrets/llm-service-account.json"
          GCP_SERVICE_ACCOUNT: "llm-service-account@xenon-depth-434717-n0.iam.gserviceaccount.com"
          LOCATION: "us-central1"
        run: pipenv run pytest src/tests/
